server:
  port: 8087
spring:
  application:
    name: provider-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#    bus:
#      trace:
#        enabled: true