##################guns配置####################
guns:
  muti-datasource-open: true #是否开启多数据源(true/false)
##################spring配置############################
########工作流配置##########
flowable:
  check-process-definitions: false #flowable自动部署的设置
  #database-schema-update: true
#server:
  #port: 8091
elasticsearch:
  ip: 127.0.0.1
  port: 9300
  cluster.name: elasticsearch
#mongodb:
  #host: 127.0.0.1
  #port: 27017
  #mongo数据库名
  #database: ceshi_database
seata:
  enabled: true
  application-id: provider-server
  tx-service-group: my_test_tx_group
  #enable-auto-data-source-proxy: true
  #data-source-proxy-mode: AT
  #enableAutoDataSourceProxy: false
  #config:
    #type: nacos
    #nacos:
      #namespace:
      #serverAddr: localhost
      #group: SEATA_GROUP
      #userName: ""
      #password: ""
  #registry:
    #type: nacos
    #nacos:
      #application: seata-server
      #server-addr: localhost
      #namespace:
      #userName: ""
      #password: ""

spring:
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    db-name: test
    #url: jdbc:mysql://49.232.161.254:3306/test?serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    #username: root
    #password: liyong123456
    #db-name: test
    driver-class-name: com.mysql.jdbc.Driver
  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
mybatis-plus:
  mapper-locations: classpath:com/provider/project/dao/**/*.xml
  type-aliases-package: com.provider.project.model
  global-config:
     id-type: 1  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
     db-column-underline: false
     refresh-mapper: true
     logic-delete-value: 1
     logic-not-delete-value: 0
  configuration:
     map-underscore-to-camel-case: false
     cache-enabled: true #配置的缓存的全局开关
     callSettersOnNulls: true #Mybatis查询数据库空字段不返回
     lazyLoadingEnabled: true #延时加载的开关
     multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
