server:
  port: 8085
  #servlet:
    #context-path: /consumer #接口前缀
spring:
  application:
    name: consumer-server
eureka:
  client:
    serviceUrl:
      #defaultZone: http://admin:admin@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
provider-server:  #这个是调用provider的服务
  NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true #feign配合hystrix 使用，从而开启Feign对Hystrix的支持




