server:
  port: 8085
spring:
  application:
    name: consumer-server
eureka:
  client:
    serviceUrl:
      #defaultZone: http://admin:admin@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

